 #include<catch.hpp>
#include<testHelper.h>
#include <nurbs/NURBSAPIExplode.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <topology/TopoCast.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Cone.hpp>
#include <geometry/Geom3HyperbolicSurface.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3OffsetSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Cone.hpp>
#include <geometry/Geom3HyperbolicSurface.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3OffsetSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp>
#include <geometry/Geom3SweepSurface.hpp"
{