 #include<catch.hpp>
#include<testHelper.h>
#include <modeling/MakeFace.hpp>
#include <topology/BRepExtremaProximityTool.hpp>
#include <modeling/TransformShape.hpp>
#include <topology/TopoTool.hpp>
#include <io/ShapeTool.hpp>
#include <topology/TopoFace.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <topology/TopoExplorer.hpp>
#include <modeling/TransformShape.hpp>
#include <topology/TopoEdge.hpp>
#include <modeling/MakeEdge2d.hpp>
#include <topology/TopoTool.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <topology/TopoVertex.hpp>
#include <math/LinearAlgebra.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/GeomAPIExtremaCurveCurve.hpp>
#include <geometry/GeomAPIProjectCurveOnSurface.hpp>
#include <geometry/Geom2BSplineCurve.hpp>
#include <geometry/Geom2Surface.hpp>
#include <geometry/Geom2BSplineSurface.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/GeomAPIExtremaCurveCurve.hpp>
#include <geometry/GeomAPIProjectCurveOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnCurve2.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectCurve2OnCurve2.hpp>
#include <geometry/GeomAPIProjectCurve3OnCurve3.hpp>
#include <geometry/GeomAdaptorCurve3.hpp>
#include <geometry/GeomAdaptorCurve2.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorCurveOnSurface.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/GeomAPIExtremaDistShapeShape.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/ShapeAnalyser.hpp>
#include <topology/TopoTool.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <geometry/GeomAPIApproxCurve3.hpp>
#include <geometry/GeomAPIExtremaDistShapeShape.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIProjectCurveOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectCurve2OnCurve2.hpp>
#include <geometry/GeomAPIProjectCurve3OnCurve3.hpp>
#include <geometry/GeomAdaptorCurve3.hpp>
#include <geometry/GeomAdaptorCurve2.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorCurveOnSurface.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/GeomAPIExtremaDistShapeShape.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIIntCurveCurve.hpp>
#include <geometry/GeomAPIProjectCurveOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectCurve2OnCurve2.hpp>
#include <geometry/GeomAPIProjectCurve3OnCurve3.hpp>
#include <geometry/GeomAdaptorCurve3.hpp>
#include <geometry/GeomAdaptorCurve2.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorCurveOnSurface.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/GeomAPIExtremaDistShapeShape.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIIntCurveCurve.hpp>
#include <geometry/GeomAPIProjectCurveOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectCurve2OnCurve2.hpp>
#include <geometry/GeomAPIProjectCurve3OnCurve3.hpp>
#include <geometry/GeomAdaptorCurve3.hpp>
#include <geometry/GeomAdaptorCurve2.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorSurface.hpp>
#include <geometry/GeomAdaptorCurveOnSurface.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/GeomAPIExtremaDistShapeShape.hpp"
{