 #include<catch.hpp>
#include<testHelper.h>
#include <boolean/BoolBRepFuse.hpp>
#include <modeling/MakeTorus.hpp>
#include <modeling/MakeSphere.hpp>
#include <modeling/MakeCone.hpp>
#include <modeling/MakePolygonFace.hpp>
#include <topomesh/BRepMeshIncrementalMesh.hpp>
#include <io/OBJTool.hpp>
#include <io/STLTool.hpp>
#include <geometry/GlobalProperty.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoFaceClassifier.hpp>
#include <math/TriangularMesh.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/TopoTool.hpp>
#include <modeling/MakeFace.hpp>
#include <topology/TopoTool.hpp>
#include <boolean/BoolBRepCut.hpp>
#include <topology/TopoCast.hpp>
#include <modeling/MakePrism.hpp>
#include <topology/TopoExplorer.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeEdge2d.hpp>
#include <topology/TopoTool.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3BSplineCurve2d.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3CylindricalSurface.hpp>
#include <geometry/Geom3SweptSurface.hpp>
#include <geometry/Geom3SurfaceOfExtrusion.hpp>
#include <geometry/Geom3SurfaceOfRevolution.hpp>
#include <geometry/Geom3SurfaceOfSweep.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BSplineCurve3.hpp>
#include <geometry/Geom3BezierCurve3.hpp>
#include <geometry/Geom3BSplineCurve2.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3BSplineSurface3.hpp>
#include <geometry/Geom3BSplineSurface2.hpp>
#include <geometry/Geom3BSplineSurface1.hpp>
#include <geometry/Geom3BSplineCurve1.hpp>
#include <geometry/Geom3BSplineCurve2.hpp>
#include <geometry/Geom3BSplineCurve3.hpp>
#include <geometry/Geom3BSplineCurve4.hpp>
#include <geometry/Geom3BSplineCurve5.hpp>
#include <geometry/Geom3BSplineCurve6.hpp>
#include <geometry/Geom3BSplineCurve7.hpp>
#include <geometry/Geom3BSplineCurve8.hpp>
#include <geometry/Geom3BSplineCurve9.hpp>
#include <geometry/Geom3BSplineCurve10.hpp>
#include <geometry/Geom3BSplineCurve11.hpp>
#include <geometry/Geom3BSplineCurve12.hpp>
#include <geometry/Geom3BSplineCurve13.hpp>
#include <geometry/Geom3BSplineCurve14.hpp>
#include <geometry/Geom3BSplineCurve15.hpp>
#include <geometry/Geom3BSplineCurve16.hpp>
#include <geometry/Geom3BSplineCurve17.hpp>
#include <geometry/Geom3BSplineCurve18.hpp>
#include <geometry/Geom3BSplineCurve19.hpp>
#include <geometry/Geom3BSplineCurve20.hpp>
#include <geometry/Geom3BSplineCurve21.hpp>
#include <geometry/Geom3BSplineCurve22.hpp>
#include <geometry/Geom3BSplineCurve23.hpp>
#include <geometry/Geom3BSplineCurve24.hpp>
#include <geometry/Geom3BSplineCurve25.hpp>
#include <geometry/Geom3BSplineCurve26.hpp>
#include <geometry/Geom3BSplineCurve27.hpp>
#include <geometry/Geom3BSplineCurve28.hpp>
#include <geometry/Geom3BSplineCurve29.hpp>
#include <geometry/Geom3BSplineCurve30.hpp>
#include <geometry/Geom3BSplineCurve31.hpp>
#include <geometry/Geom3BSplineCurve32.hpp>
#include <geometry/Geom3BSplineCurve33.hpp>
#include <geometry/Geom3BSplineCurve34.hpp>
#include <geometry/Geom3BSplineCurve35.hpp>
#include <geometry/Geom3BSplineCurve36.hpp"
{