 #include<catch.hpp>
#include<testHelper.h>
#include<common/Exception.hpp>
#include <modeling/MakeRightPrism.hpp>
#include <hatch/BRepClassificationTools.hpp>
TEST_CASE("case1 MakeRightPrism(p1, p2, nside, height, true) ", "[modeling][MakeRightPrism][P1]")
{
    Point3 p1(-2.0, 0.0, 0.0);
    Point3 p2(2.0, 0.0, 0.0);
    int nside = 6;
    double height = 4.0;
    std::vector<Point3> points;
    points.push_back(p1);
    points.push_back(p2);
    std::shared_ptrimporteoiooioiiooiooiooiooiiooiiooiooiooiooiiooiooiiooiiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooiooiooiiooiooiiooiooioo"}