 #include<catch.hpp>
#include<testHelper.h>
#include <boolean/BoolBRepSection.hpp>
#include <common/CartesianCoordinateSystem.hpp>
#include <math/LineT.hpp>
#include <modeling/MakePrism.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeFace.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge2d.hpp>
#include <modeling/MakeFace2d.hpp>
#include <modeling/MakeVertex2d.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceOfExponentialMap.hpp>
#include <geometry/Geom3SurfaceOfHyperbolicMap.hpp>
#include <geometry/Geom3SurfaceOfLinearMap.hpp>
#include <geometry/Geom3SurfaceOfLogarithmicMap.hpp>
#include <geometry/Geom3SurfaceOfSphericalMap.hpp>
#include <geometry/Geom3ToroidalSurface.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom2BezierCurve.hpp>
#include <geometry/Geom2BSplineCurve.hpp>
#include <geometry/Geom2Circle.hpp>
#include <geometry/Geom2Ellipse.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/Geom2Line.hpp>
#include <geometry/Geom2OffsetCurve.hpp>
#include <geometry/Geom2Parabola.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/Geom2Surface.hpp>
#include <geometry/Geom2SurfaceOfHyperbolicMap.hpp>
#include <geometry/Geom2SurfaceOfLogarithmicMap.hpp>
#include <geometry/Geom2SurfaceOfSphericalMap.hpp>
#include <geometry/Geom2SurfaceOfSpiral.hpp>
#include <geometry/Geom2ToroidalSurface.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/GeomAlgebraicSurface.hpp>
#include <geometry/GeomAPIExtremaCurveCurve3.hpp>
#include <geometry/GeomAPIIntSurfaceSurface.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectPointOnCurve2.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectVertexOnCurve3.hpp>
#include <geometry/GeomAPIProjectVertexOnCurve2.hpp>
#include <geometry/GeomAPIProjectVertexOnSurface.hpp>
#include <geometry/GeomAPIRebuildCurve.hpp>
#include <geometry/GeomAPIRebuildSurface.hpp>
#include <geometry/GeomAPITrimmedSurface.hpp>
#include <geometry/GeomAPITransformShape.hpp>
#include <geometry/GeomAPIWeld.hpp>
#include <geometry/GeomBezierCurve.hpp>
#include <geometry/GeomBSplineCurve2.hpp>
#include <geometry/GeomBSplineCurve.hpp>
#include <geometry/GeomCylindricalSurface.hpp>
#include <geometry/GeomExplode.hpp>
#include <geometry/GeomIntOffsetCurve.hpp>
#include <geometry/GeomIntSurfaceSurface.hpp>
#include <geometry/GeomLine2.hpp>
#include <geometry/GeomLine.hpp>
#include <geometry/GeomOffsetCurve.hpp>
#include <geometry/GeomPlane.hpp>
#include <geometry/GeomPolynomialSet.hpp>
#include <geometry/GeomSurface.hpp>
#include <geometry/GeomSurfaceOfBicubicSpline.hpp>
#include <geometry/GeomSurfaceOfBezierSurface.hpp>
#include <geometry/GeomSurfaceOfBSplineSurface.hpp>
#include <geometry/GeomSurfaceOfExponentialMap.hpp>
#include <geometry/GeomSurfaceOfHyperbolicMap.hpp>
#include <geometry/GeomSurfaceOfLinearMap.hpp>
#include <geometry/GeomSurfaceOfLogarithmicMap.hpp>
#include <geometry/GeomSurfaceOfSphericalMap.hpp>
#include <geometry/GeomSurfaceOfSpiral.hpp>
#include <geometry/GeomSurfaceOfToroidalSurface.hpp>
#include <geometry/GeomToBRep.hpp>
#include <geometry/GeomTrimmedCurve.hpp>
#include <geometry/GeomTrimmedSurface.hpp>
#include <geometry/GeomTrimmedCurve2.hpp>
#include <geometry/GeomTrimmedCurve3.hpp>
#include <geometry/GeomTrimmedSurface2.hpp>
#include <geometry/GeomTrimmedSurface3.hpp>
#include <geometry/GeomVertex.hpp>
#include <geometry/GeomVertex2.hpp>
#include <geometry/GeomVertex3.hpp>
#include <geometry/Geom2BSplineSurface.hpp>
#include <geometry/Geom2BezierSurface.hpp>
#include <geometry/Geom2Surface.hpp>
#include <geometry/Geom2SurfaceOfBezierSurface.hpp>
"
{