 #include <catch.hpp>
#include <testHelper.h>
#include <common/PointT.hpp>
#include <modeling/MakeFace.hpp>
#include <modeling/MakeEdge.hpp>
#include <topology/BRepExtremaProximityTool.hpp>
#include <modeling/MakeVertex.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoFace.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoVertex.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Adaptor3dCurveOnSurface.hpp>
#include <geometry/AdaptorGeom2Curve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/GeometryTool.hpp>
#include <geometry/GlobalProperty.hpp>
#include <geometry/LocalProperty.hpp>
#include <healing/BRepExtremaDistShapeShape.hpp>
#include <io/OBJTool.hpp>
#include <modeling/MakeShapeTool.hpp>
#include <modeling/MakeRevol.hpp>
#include <modeling/MakePrism.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeFace.hpp>
#include <topology/BRepAdaptorCurve3.hpp>
#include <topology/BRepAdaptorSurface.hpp>
#include <topology/BRepExtremaDistShapeShape.hpp>
#include <topology/BRepTool.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoFace.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoVertex.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Adaptor3dCurveOnSurface.hpp>
#include <geometry/AdaptorGeom2Curve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/GeometryTool.hpp>
#include <geometry/GlobalProperty.hpp>
#include <geometry/LocalProperty.hpp>
#include <healing/BRepExtremaDistShapeShape.hpp>
#include <io/OBJTool.hpp>
#include <modeling/MakeShapeTool.hpp>
#include <modeling/MakeRevol.hpp>
#include <modeling/MakePrism.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeFace.hpp>
#include <topology/BRepAdaptorCurve3.hpp>
#include <topology/BRepAdaptorSurface.hpp>
#include <topology/BRepExtremaDistShapeShape.hpp>
#include <topology/BRepTool.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoFace.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoVertex.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Adaptor3dCurveOnSurface.hpp>
#include <geometry/AdaptorGeom2Curve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/GeometryTool.hpp>
#include <geometry/GlobalProperty.hpp>
#include <geometry/LocalProperty.hpp>
#include <healing/BRepExtremaDistShapeShape.hpp>
#include <io/OBJTool.hpp>
#include <modeling/MakeShapeTool.hpp>
#include <modeling/MakeRevol.hpp>
#include <modeling/MakePrism.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeFace.hpp>
#include <topology/BRepAdaptorCurve3.hpp>
#include <topology/BRepAdaptorSurface.hpp>
#include <topology/BRepExtremaDistShapeShape.hpp>
#include <topology/BRepTool.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoFace.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoVertex.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Adaptor3dCurveOnSurface.hpp>
#include <geometry/AdaptorGeom2Curve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/GeometryTool.hpp>
#include <geometry/GlobalProperty.hpp>
#include <geometry/LocalProperty.hpp>
#include <healing/BRepExtremaDistShapeShape.hpp>
#include <io/OBJTool.hpp>
#include <modeling/MakeShapeTool.hpp>
#include <modeling/MakeRevol.hpp>
#include <modeling/MakePrism.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/"
{