 #include<catch.hpp>
#include<testHelper.h>
#include <modeling/MakeEdge.hpp>
#include <topology/TopoEdge.hpp>
#include <modeling/MakeVertex.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Adaptor3CurveOnSurface.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/GeomAPIExtremaCurveCurve3.hpp>
#include <geometry/ShapeClassifier.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3Point.hpp>
#include <geometry/Geom3Sphere.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Cone.hpp>
#include <geometry/Geom3Cylinder.hpp>
#include <geometry/Geom3Edge2d.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Ellipse2d.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Hyperbola2d.hpp>
#include <geometry/Geom3OffsetCurve2d.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/Geom3Parabola2d.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceOfExtrusion.hpp>
#include <geometry/Geom3SurfaceOfRevolution.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/GeomAPIExtremaCurveCurve3.hpp>
#include <geometry/ShapeClassifier.hpp>
#include <modeling/MakeFace.hpp>
#include <modeling/MakeRevol.hpp>
#include <modeling/MakeEdge2d.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/BRepAdaptorCurve3.hpp>
#include <topology/BRepAdaptorSurface.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoShape.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoVertex.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/GeomAPIExtremaCurveCurve3.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3Point.hpp>
#include <geometry/Geom3Sphere.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Cone.hpp>
#include <geometry/Geom3Cylinder.hpp>
#include <geometry/Geom3Edge2d.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Ellipse2d.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Hyperbola2d.hpp>
#include <geometry/Geom3OffsetCurve2d.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/Geom3Parabola2d.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceOfExtrusion.hpp>
#include <geometry/Geom3SurfaceOfRevolution.hpp>
#include <geometry/Geom3TrimmedSurface.hpp>
#include <geometry/Geom3BezierSurface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <topology/BRepAdaptorCurve3.hpp>
#include <topology/BRepAdaptorSurface.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeVertex.hpp>
#include <modeling/MakeEdge2d.hpp>
#include <modeling/MakeRevol.hpp>
using namespace AMCAX;
TEST_CASE("case1: this is a test case for MakeEdge", "[modeling][MakeEdge]") {
	SECTION("Test1") {
        Point3 p1"}