 #include<catch.hpp>
#include<testHelper.h>
#include <common/PointT.hpp>
#include <math/Intersect2d.hpp>
#include <geometry/MakeEdge2d.hpp>
#include <geometry/GeometryTool.hpp>
#include <geometry/PropertyTool.hpp>
#include <modeling/MakeEdge.hpp>
#include <modeling/MakeFace.hpp>
#include <modeling/MakePolygon.hpp>
#include <geometry/Geom2BezierCurve.hpp>
#include <geometry/Geom2BSplineCurve.hpp>
#include <geometry/Geom2Circle.hpp>
#include <geometry/Geom2Ellipse.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/Geom2Line.hpp>
#include <geometry/Geom2Parabola.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <geometry/GlobalProperty.hpp>
#include <geometry/Geom2Line.hpp>
#include <geometry/Geom2OffsetCurve.hpp>
#include <geometry/Geom2PolynomialCurve.hpp>
#include <geometry/Geom2SphericalCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/GeomAPIExtremaCurveCurve3.hpp>
#include <geometry/GeomAPIProjectPointOnCurve3.hpp>
#include <geometry/GeomAPIProjectPointOnCurve2.hpp>
#include <geometry/GeomAPIProjectPointOnSurface.hpp>
#include <geometry/GeomAPIProjectVertexOnCurve3.hpp>
#include <geometry/GeomAPIProjectVertexOnCurve2.hpp>
#include <geometry/GeomAPIProjectVertexOnSurface.hpp>
#include <geometry/GeomAPIProjectShapeOnSurface.hpp>
#include <geometry/GeomAPIRebuildCurve.hpp>
#include <geometry/GeomAPITransformCurve.hpp>
#include <geometry/GeomAPITransformShape.hpp>
#include <geometry/GeomAPITrimmedCurve.hpp>
#include <geometry/GeomAPIWeld.hpp>
#include <geometry/GeomAPIWeldVertex.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3CurveTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3CurveTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3CurveTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3CurveTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve.hpp>
#include <geometry/Geom3SphericalCurve.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SurfaceCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Curve.hpp>
#include <geometry/Geom3CurveTool.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3PolynomialCurve"
{