 #include<catch.hpp>
#include<testHelper.h>
#include <modeling/MakeFace.hpp>
#include <modeling/MakeEdge.hpp>
#include <topology/BRepExtremaProximityTool.hpp>
#include <modeling/MakeVertex.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <modeling/MakeWire.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3OffsetSurface.hpp>
#include <geometry/Geom3Hyperbola.hpp>
#include <geometry/Geom3Ellipse.hpp>
#include <geometry/Geom3Line3.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoCast.hpp>
#include <topology/TopoFace.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoWire.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Geom3Parabola.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <geometry/Geom3Ellipse2.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3Sphere.hpp>
#include <geometry/Geom3Torus.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3InfinitePlane.hpp>
#include <geometry/Geom3Conic.hpp>
#include <geometry/Geom3Geom2BSplineCurve.hpp>
#include <geometry/Geom3Geom2BSplineSurface.hpp>
#include <geometry/Geom3Geom2Circle.hpp>
#include <geometry/Geom3Geom2OffsetSurface.hpp>
#include <geometry/Geom3Geom2Hyperbola.hpp>
#include <geometry/Geom3Geom2Ellipse.hpp>
#include <geometry/Geom3Geom2Line3.hpp>
#include <geometry/Geom3Geom2TrimmedCurve.hpp>
#include <geometry/Geom3Geom2Parabola.hpp>
#include <geometry/Geom3Geom2Ellipse2.hpp>
#include <geometry/Geom3Geom2BezierCurve.hpp>
#include <geometry/Geom3Geom2Sphere.hpp>
#include <geometry/Geom3Geom2Torus.hpp>
#include <geometry/Geom3Geom2Plane.hpp>
#include <geometry/Geom3Geom2InfinitePlane.hpp>
#include <geometry/Geom3Geom2Conic.hpp>
#include <topology/BRepExtremaDistShapeShape.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <geometry/Geom3Geom2Geom2BSplineCurve.hpp>
#include <geometry/Geom3Geom2Geom2BSplineSurface.hpp>
#include <geometry/Geom3Geom2Geom2Circle.hpp>
#include <geometry/Geom3Geom2Geom2OffsetSurface.hpp>
#include <geometry/Geom3Geom2Geom2Hyperbola.hpp>
#include <geometry/Geom3Geom2Geom2Ellipse.hpp>
#include <geometry/Geom3Geom2Geom2Line3.hpp>
#include <geometry/Geom3Geom2Geom2TrimmedCurve.hpp>
#include <geometry/Geom3Geom2Geom2Parabola.hpp>
#include <geometry/Geom3Geom2Geom2Ellipse2.hpp>
#include <geometry/Geom3Geom2Geom2BezierCurve.hpp>
#include <geometry/Geom3Geom2Geom2Sphere.hpp>
#include <geometry/Geom3Geom2Geom2Torus.hpp>
#include <geometry/Geom3Geom2Geom2Plane.hpp>
#include <geometry/Geom3Geom2Geom2InfinitePlane.hpp>
#include <geometry/Geom3Geom2Geom2Conic.hpp>
#include <topology/TopoExplorerTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoTool.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom2BSplineCurve.hpp>
#include <geometry/Geom2BSplineSurface.hpp>
#include <geometry/Geom2Circle.hpp>
#include <geometry/Geom2OffsetSurface.hpp>
#include <geometry/Geom2Hyperbola.hpp>
#include <geometry/Geom2Ellipse.hpp>
#include <geometry/Geom2Line3.hpp>
#include <geometry/Geom2TrimmedCurve.hpp>
#include <geometry/Geom2Parabola.hpp>
#include <geometry/Geom2Geom2BSplineCurve.hpp>
#include <geometry/Geom2Geom2BSplineSurface.hpp>
#include <geometry/Geom2Geom2Circle.hpp>
#include <geometry/Geom2Geom2OffsetSurface.hpp>
#include <geometry/Geom2Geom2Hyperbola.hpp>
#include <geometry/Geom2Geom2Ellipse.hpp>
#include <geometry/Geom2Geom2Line3.hpp>
#include <geometry/Geom2Geom2TrimmedCurve.hpp>
#include <geometry/Geom2Geom2Parabola.hpp>
#include <geometry/Geom2Geom2Ellipse2.hpp>
#include <geometry/Geom2Geom2BezierCurve.hpp>
#include <geometry/Geom2Geom2Sphere.hpp"
{