 #include<catch.hpp>
#include<testHelper.h>
#include <modeling/MakeFace.hpp>
#include <modeling/MakeEdge.hpp>
#include <hatch/BRepClassificationTools.hpp>
#include <topology/TopoEdge.hpp>
#include <topology/TopoFace.hpp>
#include <modeling/MakeShape.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoTool.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <healing/ShapeFixTool.hpp>
#include <healing/ShapeFixGlobalProperty.hpp>
#include <healing/ShapeFixShape.hpp>
#include <topomesh/BRepMeshIncrementalMesh.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoCast.hpp>
#include <topology/TopoVertex.hpp>
#include <topology/TopoWire.hpp>
#include <topology/TopoTool.hpp>
#include <topology/TopoExplorer.hpp>
#include <topology/TopoShape.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/Geom3CylSurface.hpp>
#include <geometry/Geom3Sphere.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/GeomAPIInterpolate.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3CylSurface.hpp>
#include <geometry/Geom3EllipticSurface.hpp>
#include <geometry/Geom3HyperbolicSurface.hpp>
#include <geometry/Geom3ParabolaSurface.hpp>
#include <geometry/Geom3Plane.hpp>
#include <geometry/Geom3Circle.hpp>
#include <geometry/Geom3ConicalSurface.hpp>
#include <geometry/Geom3SphericalSurface.hpp>
#include <geometry/Geom3EllipticSurface.hpp>
#include <geometry/Geom3HyperbolicSurface.hpp>
#include <geometry/Geom3ProjectableCurve3.hpp>
#include <geometry/Geom3BezierCurve.hpp>
#include <geometry/Geom3BSplineCurve.hpp>
#include <geometry/Geom3TrimmedCurve.hpp>
#include <geometry/Geom3Line.hpp>
#include <geometry/Geom3Curve2d.hpp>
#include <geometry/Geom3BezierCurve2d.hpp>
#include <geometry/Geom3BSplineCurve2d.hpp>
#include <geometry/Geom3TrimmedCurve2d.hpp>
#include <geometry/Geom3Line2d.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3Ellipse2d.hpp>
#include <geometry/Geom3Hyperbola2d.hpp>
#include <geometry/Geom3Parabola2d.hpp>
#include <geometry/Geom3Circle2d.hpp>
#include <geometry/Geom3ConicalSurface2d.hpp>
#include <geometry/Geom3SphericalSurface2d.hpp>
#include <geometry/Geom3EllipticSurface2d.hpp>
#include <geometry/Geom3HyperbolicSurface2d.hpp>
#include <geometry/Geom3ProjectableCurve2d.hpp>
#include <geometry/Geom3BezierCurve2d.hpp>
#include <geometry/Geom3BSplineCurve2d.hpp>
#include <geometry/Geom3TrimmedCurve2d.hpp>
#include <geometry/Geom3Line2d.hpp>
#include <geometry/Geom3OffsetCurve2d.hpp>
#include <geometry/Geom3Ellipse2d.hpp>
#include <geometry/Geom3Hyperbola2d.hpp>
#include <geometry/Geom3Parabola2d.hpp>
#include <geometry/Geom3Circle2d.hpp>
#include <geometry/Geom3ConicalSurface2d.hpp>
#include <geometry/Geom3SphericalSurface2d.hpp>
#include <geometry/Geom3EllipticSurface2d.hpp>
#include <geometry/Geom3HyperbolicSurface2d.hpp>
#include <geometry/Geom3ProjectableCurve2d.hpp>
#include <geometry/Geom3SweptCurve.hpp>
#include <geometry/Geom3SweptSurface.hpp>
#include <geometry/Geom3SweptCurve2d.hpp>
#include <geometry/Geom3SweptSurface2d.hpp>
#include <geometry/Geom3OffsetSurface.hpp>
#include <geometry/Geom3OffsetCurve.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3BSplineSurface.hpp>
#include <geometry/Geom3Surface.hpp>
#include <geometry/Geom3SweptSurface.hpp>
#include <geometry/Geom3SweptSurface2d.hpp>
#include <geometry/Geom3Swept"
{